package com.mb.codegrip.enums;

public enum PaymentStatusEnum {

	PAYMENT_DENIED,
	PAYMENT_SUCCESSFULL,
	CUSTOMER_CREATED,
	CHARGE_SUCCEEDED,
	INVOICE_SENT,
	SUBSCRIPTION_CANCELED,
	SUBSCRIPTION_ACTIVE,
	CHARGE_FAIL,
	STARTUP_PALN_ACTIVE,
	TRIAL_STARTED,
	TRIAL_EXPIRED,
	SUBSCRIPTION_INACTIVE
	
}
